In [11]:
from statsforecast.models import AutoARIMA,AutoETS,ARIMA
import pandas as pd
import numpy as np
from statsforecast import StatsForecast
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [12]:
sudden_df=pd.read_csv('../../data/simulated_data/sudden_cd_3000.csv')
sudden_df=sudden_df.drop_duplicates(subset=['drift_point'])
sudden_df=sudden_df.sort_values('drift_point',ascending=True)
sudden_df.reset_index(drop=True, inplace=True)

In [13]:
def series_reader(df,row):
    series=df.iloc[row,1]
    # remove the brackets and split the string into individual elements
    string_arr = series.replace('[','').replace(']','').split(',')

    # convert each string element to float and create a numpy array
    arr = np.array([float(x) for x in string_arr])
    return arr

In [14]:
from base_line_model import series_reader,base_line_model

In [16]:
auto_arima=AutoARIMA(seasonal=False)
auto_ets=AutoETS()
ar_3=ARIMA(order=[3,0,0])
ar_5=ARIMA(order=[5,0,0])

In [25]:
series=series_reader(sudden_df,1)

In [26]:
series

array([4.02442553, 5.50193011, 4.26071501, ..., 1.94372563, 1.74914998,
       1.78985039])

In [31]:
pd.read_csv('../../result/sudden/exp_lgbm_sudden_window_100_error.csv')

drift_point                                             series  \
0              10  [4.0244255334079, 5.50193011119722, 4.26071501...   
1              11  [4.0244255334079, 5.50193011119722, 4.26071501...   
2              12  [4.0244255334079, 5.50193011119722, 4.26071501...   
3              13  [4.0244255334079, 5.50193011119722, 4.26071501...   
4              15  [4.0244255334079, 5.50193011119722, 4.26071501...   
...           ...                                                ...   
1519         1966  [4.0244255334079, 5.50193011119722, 4.26071501...   
1520         1967  [4.0244255334079, 5.50193011119722, 4.26071501...   
1521         1968  [4.0244255334079, 5.50193011119722, 4.26071501...   
1522         1969  [4.0244255334079, 5.50193011119722, 4.26071501...   
1523         1970  [4.0244255334079, 5.50193011119722, 4.26071501...   

      testing_RMSE  testing_MAE  training_RMSE  training_MAE  
0         0.958254     0.790202       1.249325      0.967180  
1         0.986709     0.820362       1.259097      0.974928  
2         1.005686     0.834832       1.296547      1.002597  
3         0.959272     0.796173       1.265224      0.976710  
4         0.959618     0.792072       1.276617      0.987123  
...            ...          ...            ...           ...  
1519      1.117363     0.889379       1.050636      0.856249  
1520      1.105574     0.878361       1.057011      0.859875  
1521      1.114567     0.885444       1.053048      0.857236  
1522      1.146005     0.915676       1.057280      0.856211  
1523      1.120996     0.893036       1.046007      0.851678  

[1524 rows x 6 columns]

In [20]:
def base_line_model(df,model,window_size):
    error_df=pd.DataFrame({'drift_point':[],
                           'testing_RMSE':[],
                           'testing_MAE':[]})

    pred_df=pd.DataFrame()
    for row in range(len(df)):
        drift_point=df.iloc[row,0]
        all_series=series_reader(df,row)


        pred_list=[]
        if type(window_size) is int:
            training_series=all_series[:round(0.8 * len(all_series))]
            testing_series=all_series[round(0.8 * len(all_series)):]
            training_series=training_series[int(window_size)*(-1):]
            meaningful_series=np.append(training_series,testing_series)
            for i in range(len(meaningful_series)):
                if i<len(meaningful_series)-window_size:
                    training_set=meaningful_series[i:i+window_size]
                    pred=model.fit(training_set).predict(1)['mean'][0]
                    pred_list.append(pred)
            rmse=mean_squared_error(squared=False,y_true=testing_series,y_pred=pred_list)
            mae=mean_absolute_error(testing_series,pred_list)

        elif window_size=='after':
            after_drift_series=all_series[drift_point:]
            training_series = after_drift_series[:round(0.8 * len(after_drift_series))]
            testing_series = after_drift_series[round(0.8 * len(after_drift_series)):]
            for i in range(len(testing_series)):
                training_set=np.append(training_series,testing_series[:i])
                pred=model.fit(training_set).predict(1)['mean'][0]
                pred_list.append(pred)

        elif window_size=='all':
            training_series=all_series[:round(0.8 * len(all_series))]
            testing_series=all_series[round(0.8 * len(all_series)):]
            for i in range(len(testing_series)):
                training_set=np.append(training_series,testing_series[:i])
                pred=model.fit(training_set).predict(1)['mean'][0]
                pred_list.append(pred)


        rmse=mean_squared_error(squared=False,y_true=testing_series,y_pred=pred_list)
        mae=mean_absolute_error(testing_series,pred_list)

        pred_df[f'drift_point{str(drift_point)}']=pred_list
        error_df.loc[row,:]=[drift_point,rmse,mae]
    return pred_df,error_df

In [22]:
base_line_model(sudden_df,auto_arima,'all')

KeyboardInterrupt: 

In [110]:
ar_5.fit(series).predict(1)

{'mean': array([1.93379719])}

In [103]:
b

[array([1.88871183])]

In [89]:
a=pd.read_csv('../../result/sudden/exp_lgbm_sudden_window_100_error.csv')

In [38]:
a=100

In [40]:
type(a) is int

True

In [41]:
series=series_reader(sudden_df,0)

In [45]:
training_seris=series[:round(0.8 * len(series))]
testing_series=series[round(0.8 * len(series)):]

In [ ]:
for 

In [47]:
row=0
def string_to_list(string_org):
    string = string_org.split(',')
    string_list = []
    for i in range(len(string)):
        if i == 0:
            data = float(string[i][1:])

        elif i == len(string) - 1:
            data = float(string[i][:-1])
        else:
            data = float(string[i])
        string_list.append(data)
    return string_list

sudden_series_row = sudden_df.loc[row]
sudden_series = sudden_series_row[1]
sudden_series_list = string_to_list(sudden_series)
sudden_series_df = pd.DataFrame({})
sudden_series_df = pd.DataFrame({
    'drift_point': sudden_series_row.drift_point,
    'value': sudden_series_list})
for lags in range(1, 11):
        sudden_series_df['lag' + str(lags)] = sudden_series_df['value'].shift(lags).fillna(0)

In [49]:
sudden_series_df

drift_point     value      lag1      lag2      lag3      lag4      lag5  \
0              10  4.024426  0.000000  0.000000  0.000000  0.000000  0.000000   
1              10  5.501930  4.024426  0.000000  0.000000  0.000000  0.000000   
2              10  4.260715  5.501930  4.024426  0.000000  0.000000  0.000000   
3              10  5.960946  4.260715  5.501930  4.024426  0.000000  0.000000   
4              10  3.197766  5.960946  4.260715  5.501930  4.024426  0.000000   
...           ...       ...       ...       ...       ...       ...       ...   
1995           10  2.733733  2.814620  3.205647  3.389678  3.386082  3.504344   
1996           10  2.417984  2.733733  2.814620  3.205647  3.389678  3.386082   
1997           10  1.943726  2.417984  2.733733  2.814620  3.205647  3.389678   
1998           10  1.749150  1.943726  2.417984  2.733733  2.814620  3.205647   
1999           10  1.789850  1.749150  1.943726  2.417984  2.733733  2.814620   

          lag6      lag7      lag8      lag9     lag10  
0     0.000000  0.000000  0.000000  0.000000  0.000000  
1     0.000000  0.000000  0.000000  0.000000  0.000000  
2     0.000000  0.000000  0.000000  0.000000  0.000000  
3     0.000000  0.000000  0.000000  0.000000  0.000000  
4     0.000000  0.000000  0.000000  0.000000  0.000000  
...        ...       ...       ...       ...       ...  
1995  3.596305  3.701912  3.664779  3.514945  3.460599  
1996  3.504344  3.596305  3.701912  3.664779  3.514945  
1997  3.386082  3.504344  3.596305  3.701912  3.664779  
1998  3.389678  3.386082  3.504344  3.596305  3.701912  
1999  3.205647  3.389678  3.386082  3.504344  3.596305  

[2000 rows x 12 columns]

In [50]:
len(series)

2000

In [54]:
series

array([4.02442553, 5.50193011, 4.26071501, ..., 1.94372563, 1.74914998,
       1.78985039])

In [68]:
auto_arima.fit(series[-101:-1])
a=auto_arima.predict(1)['mean']


In [71]:
auto_arima.fit(series[-200:-101])
b=auto_arima.predict(1)['mean']

In [74]:
b

array([3.18093253])

In [66]:
series[-1]

1.78985038999067

In [63]:
len(series[-101:-1])

100

In [73]:
np.append(a,b)

array([1.5652964 , 3.18093253])

In [78]:
series[-100:].append(series)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [79]:
np.append(series[-100:],series)

array([2.99452639, 3.09065721, 3.269376  , ..., 1.94372563, 1.74914998,
       1.78985039])

In [80]:
len(np.append(series[-100:],series))

2100

In [81]:
len(series[0:100])

100